### ISSUE TITLE
OSVR_OVERRIDE not needed

### ISSUE THREAD

**Issue by rpavlik** [OSVR/SteamVR-OSVR#1]
Unless for some reason we need to build this with something older than MSVC 2013, we can just use `override`

**Comment by d235j** [comment]
What version of MSVC is SteamVR compiled with? It would be best to use the same compiler/C++ runtime to avoid weird issues.

**Comment by d235j** [comment]
Looks like SteamVR is compiled with MSVC 2013, which means we will always have to use MSVC 2013 for this.

Should I make this change?

**Comment by godbyk** [comment]
Keep in mind that MSVC isn't the only compiler being targeted. Other compilers may support enough C++11 to build this driver but not support the `override` keyword yet. So for maximum compatibility, I'd suggest using the `OSVR_OVERRIDE` (and `OSVR_NOEXCEPT`, etc.) keyword.

There's little cost to doing so since CMake provides the macros for us.

**Comment by d235j** [comment]
Ah, good point. The other compilers being used are likely going to be clang and gcc, and gcc might be a problem if Ubuntu 12.04 is still involved anywhere.

**Comment by godbyk** [comment]
I'm marking this as WONTFIX as it seems harmless to me.

If someone runs into problems with `OSVR_OVERRIDE`, please re-open this bug with a description of the problem encountered.
