### ISSUE TITLE
DisplayConfig refactor

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/SteamVR-OSVR#12]
Much of the display config parsing in SteamVR-OSVR has since moved into OSVR-Core. Specifically, in ClientKit's ```display.h``` (C++) or ```displayC.h``` (C). Since the display config parsing code is out of date and causing errors, it's probably a good time to replace it with code that gets the information from ClientKit.

So, ```osvr_display_configuration.h``` and ```projection_matrix.h``` can be removed I think. In ```OSVRTrackedDevice```, we need to re-implement ```GetWindowBounds```, ```GetRecommendedRenderTargetSize```, ```GetEyeOutputViewport```, ```GetProjectionRaw```, ```GetHeadFromEyePose```, ```ComputeDistortion```, ```GetIPD```. 

Also, the display config code in OSVR-Core internally subscribes to /me/head and provides pose states for you, so we can also remove for example the handler in ```OSVRTrackedDevice::HmdTrackerCallback```. The API lets you specify matrix row order and coordinate system handedness, so there shouldn't be a need to use Eigen to do the conversions. Once that is removed, look into whether there is any code that can be removed from ```matrix_cast.h```. I suspect only the final matrix/pose conversion functions will still be needed.

Note: for this iteration, it's ok to only support OSVR display configurations that will match what OpenVR expects. That would be a single display input, a single viewer, with two eyes (one surface each) mapped to the same display input. I don't believe OpenVR supports multi-input HMDs yet, so we can probably defer support for them in the plugin at this time.

A question was brought up about what to do for ```ClientDriver_OSVR::AttachToWindow```. Previously I thought this was asking the driver to actually implement the attachment to the window, but this is what the documentation says:

"[Windows only] Notifies the driver that the VR output will appear in a particular window."

I'm not exactly sure what they are expecting the HMD driver to do in response to this event, but it looks like it's called after the window has been attached elsewhere (perhaps by the game engine), so I don't think we need to do anything for this callback.

**Comment by d235j** [comment]
Based on a quick peek at Valve's Oculus driver, that function sure isn't Windows only. I'm not sure exactly what they're responding with, but it is something.

**Comment by rpavlik** [comment]
Also, with regard to the figuring out the display - that's not in OSVR Core yet due to a variety of reasons as I listed in my email. If SteamVR needs it, for now, either pick the first monitors with the right resolution, or just ask for it to be configured - there does appear to be a config file provided to steamvr drivers.

**Comment by d235j** [comment]
@rpavlik I'm aware; I'm just wondering if there's any planned solution for this that doesn't involve a full render manager.

**Comment by rpavlik** [comment]
I'd like there to be one - would be the "fabled 'display interface'" - you'd basically have plugins corresponding to displays as well as input devices, and those plugins for displays could find them (with some wrapper functions from core to make it cross-platform if possible)

**Comment by d235j** [comment]
So looking over this:
> GetRecommendedRenderTargetSize
SteamVR assumes that an HMD is always a single window or screen. OSVR does not. How do we compute this?
> GetEyeOutputViewport
I implemented this using getRelativeViewport().
> GetProjectionRaw
I implemented this using getProjectionClippingPlanes().
> GetHeadFromEyePose
How best to implement this?
> GetIPD
I don't think we have API for this at all.

Any suggestions?

**Comment by JeroMiya** [comment]
For ```GetRecommendedRenderTargetSize```, is that meant to be the actual viewport size or are they asking for extra pixels for distortion/time-warp? Either way, you can just use the display input API to get this (if they're asking for extra pixels, just scale the display input resolution by some small hard-coded factor). For now, just add support for a single display input. We'll probably need to talk to the Epic folks about supporting HMDs with multiple display inputs, but it's not a priority.

As for IPD, hard code this for now. There should be a hard-coded value in OSVR-Core - please use the same value.

As for ```GetHeadFromEyePose```, hmm. I can't remember offhand but I think you can use ```osvrClientGetViewerPose``` to get the head pose in world space, and ```osvrClientGetViewerEyePose``` to get the eye poses in world space. If so, then you should be able to use those to get the eye poses in head-space.

**Comment by d235j** [comment]
Based on https://github.com/ValveSoftware/openvr/wiki/IVRSystem::GetRecommendedRenderTargetSize, it does seem like they want some extra space. I'm uncertain how best to calculate this, as they want it "matched with the projection matrix and distortion function".

**Comment by russell-taylor** [comment]
When I tried an overfill of 1.5X on the Oculus parameters and a 10x10 distortion mesh, I got quite bad texture clamping effects.  This disappeared with an overfill of 2.0.  This does not account for large time warp needs (which would be less than this).  Given an estimate of maximum latency and motion speed and the distortion correction, we could compute an overfill ratio.  For now, I just made it a parameter -- people may want to trade this off because it could impact render speed.

**Comment by d235j** [comment]
@JeroMiya returning double the normal dimensions via GetRecommendedRenderTargetSize causes extremel performance degradation on my computer; we need to figure out a better way of computing the actual ideal render target size.

**Comment by d235j** [comment]
Initial implementation is in https://github.com/OSVR/SteamVR-OSVR/pull/14.

Is there anything that currently uses distortion with OSVR? It's going to be difficult to test as-is...

**Comment by JeroMiya** [comment]
Overfill scale factor is now part of the rendermanager configuration, which is going to be in core (there's a PR for it, but not merged). But that's an internal API (in osvrClient) without a public API yet, which will take a little time. So for now, using a 1.0 overfill factor is a reasonable default.

**Comment by yboger** [comment]
Wouldn't the overfill factor depend on how much 'timewarp' you expect to do? Does 1.0 overfill factor mean that instead of "W x H" we are asking the app to do '2W x 2H' pixels?

**Comment by russell-taylor** [comment]
Currently, the amount of overfill required depends on two things: (1) the distortion parameters, which is fixed; (2) the amount and direction (and rotation) required by timewarp, which depends on user motion, which is statistical.

We could compute for some 90th-percentile estimate of user head motion how much margin to leave and set it to that.

The reason it is a parameter is because I anticipated the performance hit required to have a high confidence that we will have enough coverage would be larger than some users would want to accept.  This makes it sort of like a "high quality, very high, insanely high" knob, which trades off frame rate (number of pixels goes up quadratically with overfill) and artifacts (chance of getting a clamped texture coordinate at the edge of the render texture).  When the clamping happens, we get a constant-color artifact near the edge of the screen.

Unfortunately, the factor of 1.5 I chose was not enough to handle the distortion mesh from the Oculus example config, which is why I changed it to 2.  No impact on my cube-world rendering on my high-end card, but that's not a good test; the above report of slowdown makes me lean towards leaving it a parameter with a default that covers most cases.

A factor of 1.0 leaves the display size the same.  A factor of 2 doubles it in each dimension, quadrupling the number of pixels rendered.

**Comment by russell-taylor** [comment]
nVidia's response to this has been their non-uniform display buffer in VR mode.  I've not looked into that.

**Comment by d235j** [comment]
@russell-taylor unfortunately VR APIs that are under NDA may not be all that helpful here, at least for me. Some platform abstraction layer may be necessary. I'm not sure what solutions the other graphics card vendors are planning to implement.

**Comment by russell-taylor** [comment]
I agree, which is what RenderManager is for.  It hides the DirectMode API in a DLL that lets you use it without having to link to it.  I don't know of plans to implement the non-uniform rendering within RenderManager (we're still pounding on latency reduction).  For now, the adjustable parameter is what we have.

We may be able to handle smaller overfills by increasing the resolution of the distortion mesh (another parameter, but it may not be exposed yet).  This would get vertices closer to the edge whose coordinates are not clipped.  Haven't though much about this.

**Comment by russell-taylor** [comment]
We're open to wrapping other vendors' APIs inside RenderManager as well.

**Comment by rpavlik** [comment]
and the DK2 (and a bunch of other HMDs, look in the Displays dir) use the distortion stuff

**Comment by yboger** [comment]
In fact, that is the point of OSVR - to create a vendor-independent abstraction layer. So we will wrap AMD, Intel and others in a similar way

**Comment by d235j** [comment]
Yep, I'm aware. I just dislike portions of the stack being locked up from community contribution due to vendor SDK restrictions — hopefully the portions of the stack locked up like this will be relatively minor.

**Comment by russell-taylor** [comment]
Amen.

**Comment by godbyk** [comment]
Is there any more work to be done on refactoring the display config in SteamVR-OSVR at this time? Or is it all pending further work in OSVR-Core and RenderManager?
