### ISSUE TITLE
SteamVR Crashing on launch

### ISSUE THREAD

**Issue by SASniper** [OSVR/SteamVR-OSVR#17]
As soon as SteamVR connects to Core it crashes, the core remains running and reports a client disconnect, I'm unsure if I can fig further into the reasons via further debug so any help is appreciated.

All SteamVR version's listed under the Steam - Beta tab have this issue except for version V1445878235 which at least allows the HMD Window to be auto launched but no further success can be had at my end.

Core Version: OSVR-Core-Snapshot-v0.6-413-g87c30a2-build199-vs12-64bit
OSVR Plugin Version: SteamVR-OSVR-Win-Build-v0.1-4-ge2e4fc2-core-v0.6-413-g87c30a2
HDK: 1.3

**Comment by SASniper** [comment]
It seems the following Pull Request could effect this issue: https://github.com/OSVR/SteamVR-OSVR/pull/16

**Comment by rpavlik** [comment]
Merged #16 - a new build should be done and up soon. Can you re-test when that's up?

**Comment by thomasgauthier** [comment]
I am still experiencing this with the latest build. VR Server crashes on launch and SteamVR gives me error code 301.

Core Version: OSVR-Core-Snapshot-v0.6-619-g5ac4700-build214-vs12-64bit
OSVR Plugin Version: SteamVR-OSVR-Win-Build-v0.1-15-g0886035-core-v0.6-619-g5ac4700
HDK: 1.3
SteamVR BuildID: 888763 (non-beta)

Here's the SteamVR vrserver log file. It says "Skipping osvr. because it is not an HMD", I don't know if it's related but it's clearly not normal.
[vrserver.txt](https://github.com/OSVR/SteamVR-OSVR/files/67270/vrserver.txt)

**Comment by SASniper** [comment]
Hey guys,

I've updated to the latest versions:

Core Version: OSVR-Core-Snapshot-v0.6-628-g9bcdeab-build215-vs12-64bit
OSVR Plugin Version: SteamVR-OSVR-Win-Build-v0.1-15-g0886035-core-v0.6-628-g9bcdeab
SteamVR Version: 1449513123 (non-beta)

I am unfortunately still encountering the same issue as before.  VRServer.exe crashes when launching SteamVR.

VRServer.txt Log
--------------------------------------------------------------
Sun Dec 20 2015 13:24:55.855 - osvr: ServerDriver_OSVR::Init() called.
Sun Dec 20 2015 13:24:55.916 - osvr: ServerDriver_OSVR::GetTrackedDeviceCount(): Detected 1 tracked devices.
Sun Dec 20 2015 13:24:55.916 - osvr: ServerDriver_OSVR::GetTrackedDeviceCount(): Detected 1 tracked devices.
Sun Dec 20 2015 13:24:55.916 - osvr: ServerDriver_OSVR::GetTrackedDeviceDriver(): Returning tracked device 0.
Sun Dec 20 2015 13:24:55.916 - Skipping osvr. because it is not an HMD
------------------------------------------------------------

**Comment by JeroMiya** [comment]
I'm still looking into this, but here are my notes so far:

Running with breakpoints in all plugin functions/methods. Results:

Call order is:
 * ```HmdDriverFactory``` function is called. Passes control through to ```TrackedDeviceDriverFactory```. ```interface_name``` is ```IServerTrackedDeviceProvider_001```.
 * ```ServerDriver_OSVR::Init``` is called. The client context is created successfully. An ```OSVR_TrackedDevice``` is created and added to the ```_trackedDevices``` list.
 * ```ServerDriver_OSVR::GetTrackedDeviceCount``` is called, twice. Both times returning 1.
 * ```ServerDriver_OSVR::GetTrackedDeviceDriver``` is called with index 0. The ```OSVR_TrackedDevice``` created in ```Init``` is returned.
 * ```OSVRTrackedDevice::GetModelNumber``` is called. "OSVR HMD" is returned.
 * On the log, I now see "Skipping osvr. because it is not an HMD". I'm not sure how it knows that, since it hasn't called any other methods on ```OSVRTrackedDevice``` aside from ```GetModelNumber```. More specifically, it hasn't called ```OSVRTrackedDevice::GetTrackedDeviceDriverInfo``` which would tell it that the device is an HMD.
 * ```ServerDriver_OSVR::GetTrackedDeviceCount``` is called again. Returns 1.
 * Crash in vrserver.exe, outside of our DLL.

**Comment by typhoidcoma** [comment]
Am I thinking this is a steamVR issue still right?  I can't get it to run anything on my end.  If I go to a really old beta of SteamVR is half ass works.  

I was reading the SteamVR boards as well and some people seem to be having a similar issue with DK2's.

**Comment by JeroMiya** [comment]
It was broken in v1449513123. v1448479831 "works" for me in that it doesn't crash and there seems to be some head tracking going on in the HMD window that pops up. I've never been able to get it working in an actual game yet.

**Comment by typhoidcoma** [comment]
I just saw this post on SteamVR, but have been at work and unable to try it, has anyone else given it a look?

-Orginal SteamVR  Post-

That was a good idea Girdus!

When I tried to run "Steam\steamapps\common\OpenVR\bin\win32\vrserver.exe", it told me that it couldn't find "steam_api.dll". I copied "steam_api.dll" from "Steam\steamapps\common\OpenVR\tools\bin\win32" to "Steam\steamapps\common\OpenVR\bin\win32\", which made it possible for me to start "vrserver.exe" without errors. 

After starting vrserver.exe manually, I could run the SteamVR application from the steam games library. The SteamVR application now guided me through setting up the headset, which worked for the Oculus Rift.

**Comment by thomasgauthier** [comment]
The issue seemed to be solved in the latest builds of both this plugin and SteamVR. To make it work the HDK must be set as an extended display in the OS settings and sit to the right of the main display (top pixels aligned).
![bo1rwme](https://cloud.githubusercontent.com/assets/9730392/12283973/cf5ab31c-b979-11e5-97d6-af8388231fd0.png)

**Comment by fieldy1** [comment]
Mine still crashes-SteamVR 301 error. I have tried al types of fixes with no joy. Lastest Core and Steam2OSVR drivers

**Comment by toxicFork** [comment]
@thomasgauthier you can also modify the config json to overwrite the position settings e.g. My OSVR display is on the left so I use 

```json
"renderManagerConfig": {
        "window": {
            "xPosition": 0,
            "yPosition": 0
        },
    }
```

**Comment by godbyk** [comment]
We've just released an updated SteamVR-OSVR driver that should work with the current release of SteamVR. Please give it a try and report back if you encounter any problems.

**Comment by godbyk** [comment]
I'm closing this isssue due to a lack of information. If you are the original filer of this issue and still encounter this problem, feel free to reopen this issue. If you're not the original filer of this issue, please open a new issue instead.
