### ISSUE TITLE
Plugin not working with latest SteamVR beta builds

### ISSUE THREAD

**Issue by DjDyll** [OSVR/SteamVR-OSVR#33]
Tested with latest core and plugin as on 1-23-16.
Wanted to make you guys aware of the problem.

Error is as follows in this screenshot:

http://prntscr.com/9udxuh

-Dylan

**Comment by toxicFork** [comment]
Let's reopen this please, we can close it when we fix it for the latest versions

**Comment by godbyk** [comment]
@DjDyll We've updated the driver so that it should work with the current version of SteamVR. It may also work with the current beta versions, but Valve often releases beta versions prior to updating the public OpenVR API for us to build against. I'd suggest sticking with the current releases whenever possible.

Please let me know if the latest SteamVR-OSVR driver works for you. If it does, we can close this issue. Thanks!
