### ISSUE TITLE
SteamVR update on 4-27-16 breaks OSVR support.

### ISSUE THREAD

**Issue by DjDyll** [OSVR/SteamVR-OSVR#48]
2/27/16 SteamVR update removed the beta builds breaking OSVR Support. While the HMD shows up as green in SteamVR with status "Not ready", SteamVR applications do not work. Compositor opens up and head tracking works. But in any application the "Blue screen" bug occurs. This bug is very interesting. if you mirror the HMD (one eye view) you can see that if you rotate the HMD, the image will rotate after a few seconds. The screen on the HMD is blue, but if the HMD is still, the screen will fade in and out of the blue screen and a black screen. The mirrored image (Apollo 11) runs smooth. Tested on both beta build and official build.
This is tested with latest core downloaded on 4-27-16, latest SteamVR drivers as of 4-27-16, and HDK 1.3.

**Comment by nanospork** [comment]
It might also be helpful to recognize that this bug first appeared with the *previous* SteamVR release. Most people had been using Beta v1457503340, but as stated that has been removed. There is also no good way to prevent Steam from auto-updating SteamVR to the latest release.

I believe the issue described here is the same as #47.

I also suspect that it may be related to #45.

**Comment by JFK-Games** [comment]
Steam support does not seem to be interresed in fixing this bug:

https://support.steampowered.com/view.php?ticketref=4650-UVBN-8743

**Comment by DjDyll** [comment]
@JFK-Games Can you copy and paste what was said? The link does not work for us.

**Comment by dos1** [comment]
I believe this is already fixed?

**Comment by nanospork** [comment]
Nope. Just tested with latest SteamVR plugin, server, and Nvidia drivers, with positional tracking enabled. Still no Room Setup, no recentering, and games are still exhibiting the blue/gray screen issue.

**Comment by JFK-Games** [comment]
@DjDyll 

Hello JFK,

Thank you for contacting Steam Support.

Unfortunately, OSVR is currently not supported with SteamVR. We suggest contacting the manufacturer for more information regarding your issue.

Thank you for your interest in SteamVR.

**Comment by stephenmsnow** [comment]
I messaged in an email thread that I've been partnered in this project for a long time, but haven't had a ton of time to dedicate to this project due to daily duties, sounds like this is as useful of a place as any to start... do we have any idea where this is broken, why, and what it's going to take to fix?  I finally have some time free to start taking at a look at the platform and would be happy to help get SteamVR support off the ground in any way I'm capable of...

**Comment by d235j** [comment]
@stephenmsnow right now the issue is that for most games, there is a blue screen or no output. The cause so far is not entirely known.

We've been discussing development on Gitter (https://gitter.im/OSVR/SteamVR-OSVR) in case you're interested in joining. I have been having difficulties getting my testing setup back together, unfortunately, but I should be able to do so hopefully within a few days.

**Comment by godbyk** [comment]
Could you give the latest build of the SteamVR-OSVR driver a try? I've updated it to work with the latest released version of OpenVR (v1.0.0) and it works for me with the latest released version (non-beta) of SteamVR. I haven't tried it with a beta release of SteamVR yet.
