### ISSUE TITLE
SteamVR doesn't work on higher resolution HMD

### ISSUE THREAD

**Issue by robsonswiss** [OSVR/SteamVR-OSVR#81]
## Description of issue

When using a 2560x1440 display, I was unable to get SteamVR working in extended mode, I was able to get the compositor working but SteamVR still said "not ready", room setup didn't work etc.

When I set my HMD resolution to 1920x1080 and scaled it using the GPU (I believe this is a Nvidia only option) everything worked immediately. It isn't clear if this is a SteamVR or SteamVR-OSVR problem.
## Steps to reproduce the problem

Use a high resolution HMD
## System configuration

GTX 980, latest drivers, latest SteamVR, latest SteamVR-OSVR

**Comment by godbyk** [comment]
@robsonswiss Would you mind giving the [latest release](https://bintray.com/osvr/SteamVR-OSVR/SteamVR-OSVR-Win/_latestVersion) a try? It's designed to fix problems with the display orientation and I think that might help. Even if it doesn't, i'll get us to a common base line and we can continue troubleshooting from there. Thanks!

**Comment by bagobor** [comment]
I got same problem with latest release as well. :((
May be my configs helps you 

[Vrvana_Totem.zip](https://github.com/OSVR/SteamVR-OSVR/files/443589/Vrvana_Totem.zip)
[tv1.extended.landscape.zip](https://github.com/OSVR/SteamVR-OSVR/files/443590/tv1.extended.landscape.zip)

**Comment by godbyk** [comment]
@bagobor Could you also attach a copy of the `vrserver.txt` file found in the `Steam\Logs` directory (wherever you have Steam installed)?

**Comment by bagobor** [comment]
@godbyk all steamvr logs attached.
[steamvr_logs.zip](https://github.com/OSVR/SteamVR-OSVR/files/446557/steamvr_logs.zip)

**Comment by bagobor** [comment]
@godbyk Do I need to manually edit SteamVR config options? Do you have any examples for that?

**Comment by godbyk** [comment]
@bagobor The `vrserver.txt` log that you attached appears to be incomplete. What is there looks correct, though.

Since you're not using an OSVR HDK, you will need to modify the `steamvr.vrsettings` file. This file should exist in the `\Program Files (x86)\Steam\config` directory. If it doesn't exist, you can create it. You will need to set the `displayName` property to match a portion of the name of your HMD's display name as provided by the product name EDID value.  The `vrserver.txt` log file should show you the detected display names (if your HMD is in extended mode).

Here is a minimal example `steamvr.vrsettings` file that you can use as a template:

```json
{
    "jsonid" : "vrsettings",
    "steamvr" : {
        "activateMultipleDrivers": true
    },
    "driver_osvr": {
        "verbose": false,
        "displayName": "OSVR",
        "scanoutOrigin": "upper-left"
    }
}
```

The `verbose` option enables or disables verbose logging of the SteamVR-OSVR driver. If you set this to `true`, it will print out a lot of debugging information to the `vrserver.txt` file.

The `scanoutOrigin` option is the position of the first pixel drawn to the screen (e.g., the upper-left pixel of the Windows desktop) when you're wearing the HMD. For example, the OSVR HDK 2 has the display installed upside-down, so the `scanoutOrigin` is set to `lower-right` for that display because the upper-left pixel of the desktop appears at the `lower-right` corner of the screen when you're wearing the OSVR HDK. If you leave this setting out, it will default to `upper-left`.

The `displayName` option, as mentioned above, is a substring that matches the display you wish to use for SteamVR. It should match the EDID product name of your HMD.

For more SteamVR-OSVR configuration settings, see the [`steamvr.vrsettings` file](https://github.com/OSVR/SteamVR-OSVR/blob/master/steamvr.vrsettings) which shows the default values.

**Comment by robsonswiss** [comment]
Hi

Just thought I'd mention that this is no longer an issue, it works fine at 2160x1200.
